export const fakeValue = {
  // OrgID: "7206207001",
  // CustomerCodeSys: "ABC",
  // NetworkID: "7206207001",
  // CustomerCode: "ABC",
  // CustomerType: null,
  // CustomerGrpCode: null,
  // CustomerSourceCode: null,
  // CustomerName: "ABC",
  // CustomerNameEN: null,
  // CustomerGender: null,
  // CustomerPhoneNo: null,
  // CustomerMobilePhone: null,
  // ProvinceCode: null,
  // DistrictCode: null,
  // WardCode: null,
  // AreaCode: null,
  // CustomerAvatarName: null,
  // CustomerAvatarSpec: null,
  // FlagCustomerAvatarPath: null,
  // CustomerAvatarPath: null,
  // JsonCustomerInfo:
  //   '[{"ColCodeSys":"CUSTOMGROUP","ColValue":"22"},{"ColCodeSys":"CUSTOMTYPE","ColValue":"Cá nhân"},{"ColCodeSys":"COMPANY","ColValue":"CTY TNHH ABC"},{"ColCodeSys":"CUSTOMSOURCE","ColValue":"44"},{"ColCodeSys":"DEPARTMENTFIELD","ColValue":"O"},{"ColCodeSys":"EMAIL","ColValue":"tienanh17082001@gmail.com"},{"ColCodeSys":"PHONE1","ColValue":"123456789012"},{"ColCodeSys":"APARTMENTNUMBER, STREET","ColValue":"343 trần cung"}]',
  // CustomerAddress: null,
  // CustomerEmail: null,
  // CustomerDateOfBirth: null,
  // GovIDType: null,
  // GovIDCardNo: null,
  // GovIDCardDate: null,
  // GovIDCardPlace: null,
  // TaxCode: null,
  // BankCode: null,
  // BankName: null,
  // BankAccountNo: null,
  // RepresentName: null,
  // RepresentPosition: null,
  // UserCodeOwner: null,
  // ContactName: null,
  // ContactPhone: null,
  // ContactEmail: null,
  // Fax: null,
  // Facebook: null,
  // InvoiceCustomerName: null,
  // InvoiceCustomerAddress: null,
  // InvoiceOrgName: null,
  // InvoiceEmailSend: null,
  // MST: null,
  // ListOfCustDynamicFieldValue: null,
  // FlagDealer: null,
  // FlagSupplier: null,
  // FlagEndUser: null,
  // FlagShipper: null,
  // FlagBank: null,
  // FlagInsurrance: null,
  // DTimeUsed: null,
  // CreateDTimeUTC: "2023-06-02 12:55:12",
  // CreateBy: "0317844394@INOS.VN",
  // LUDTimeUTC: "2023-06-02 12:55:12",
  // LUBy: "0317844394@INOS.VN",
  // FlagActive: "1",
  // Remark: null,
  // Coordinates: null,
  // LogLUDTimeUTC: "2023-06-02 12:55:12",
  // LogLUBy: "0317844394@INOS.VN",
  // Org_NNTFullName: "CÔNG TY CỔ PHẦN QUỐC TẾ LONG QUANG",
  // Network_NNTFullName: "CÔNG TY CỔ PHẦN QUỐC TẾ LONG QUANG",
  // mct_CustomerTypeName: null,
  // mcg_CustomerGrpName: null,
  // mcs_CustomerSourceName: null,
  // mp_ProvinceName: null,
  // md_DistrictName: null,
  // mw_WardName: null,
  // ma_AreaName: null,
  // mg_GovIDTypeName: null,
  // SolutionCode: null,
  // FunctionActionType: null,
  // Setting: null,
  // CustomDataDict: {},
};
